### ISSUE TITLE
Exceptions are printed out too verbosely

### ISSUE THREAD

**Issue by tgs** [psexton/matlab-xunit#1]
The stack trace doesn't have anything to do with the actual test failure:

<pre>
===== Test Case Failure =====
Location: /home/tgs/multi-lib/data-analysis/cevent/cevent_relative_intervals.m
Name:     cevent_relative_intervals

/home/tgs/src/xunit-git/xunit/DocTest.m at line 203
/home/tgs/src/xunit-git/xunit/DocTest.m at line 100
/home/tgs/src/xunit-git/xunit/TestSuite.m at line 85
/home/tgs/src/xunit-git/xunit/TestSuite.m at line 85
/home/tgs/src/xunit-git/xunit/TestSuite.m at line 85
/home/tgs/src/xunit-git/xunit/runtests.m at line 126

DocTest #4 from cevent_relative_intervals failed; expected first, got second
Inputs are not equal.

First input:
ans = 1 10 1 21 21 2 81 85 3

Second input:
??? Error using ==> cevent_relative_intervals at 76 The WHENCE argument must be either 'start' or 'end'.
</pre>

**Comment by psexton** [comment]
This issue was moved to psexton/matlab-xunit-doctests#1
