### ISSUE TITLE
`localfunctions` function was only added in R2013b

### ISSUE THREAD

**Issue by Nzbuu** [psexton/matlab-xunit#21]
I think that the new subfunction test suites are incompatible with versions of MATLAB before R2013b, since that's when the `localfunctions` function was added in MATLAB.

I think this is a particular problem since people who know that they're only using R2013b or newer are likely to be using matlab.unittest instead.

**Comment by bauglir** [comment]
You are right, they are 'incompatible' with versions prior to R2013b. There is a note on this in the [documentation](https://cdn.rawgit.com/psexton/matlab-xunit/master/doc/html/compatibilityWith2016b.html#7) as well as in the help for [`buildFunctionHandleTestSuite`](https://github.com/psexton/matlab-xunit/blob/master/src/buildFunctionHandleTestSuite.m). The `initTestSuite` warning refers to this help location.

If you want to support _both_ versions prior to R2013b and later than R2016b you need to jump through these additional hoops. Prior to R2013b you can just continue using `initTestSuite` (although the warnings may get a bit annoying). After R2014b you can always use `localfunctions` (if you happen to use subfunction test suites inside packages you _have_ to use the prior to R2013b method as well as `localfunctions` doesn't get handles to those functions properly in those versions).

I tried very hard to abstract this difference away into some common function, but was unable to do so. This is mentioned at the start of the documentation page I linked at the start of this post.

Out of the box, the only tests that should break are in the category 'packaged' case I just mentioned. All other cases of using `initTestSuite` should work just fine.

As a sidenote, I have to disagree with your final statement. I have a large library of tests which are all written using the xUnit framework. I target only the 4 more recent versions of MATLAB, but I have no intention of migrating to `matlab.unittest`. I cannot imagine I'm the only one.

**Comment by Nzbuu** [comment]
I think that the biggest problem in this respect is that the tests on the xunit framework itself won't run before R2013b. The framework must be able to test itself on every supported platform.

Maybe it's more of a personal preference, but I think it would be better for this framework to focus on having full support for earlier versions of MATLAB, with limitations in later version of MATLAB where necessary.

**Comment by bauglir** [comment]
You are totally right about the test suite not running. That was an oversight on my part. I've submitted a PR addressing the issue.

As far as I'm aware, technically, the current version of the framework has the exact same capabilities as the previous version. Only on R2016b and later is it _absolutely_ necessary to directly use `buildFunctionHandleTestSuite`. All older versions can simply use `initTestSuite` as I've mentioned previously.

I could totally see the `warning` being an issue and possibly getting rid of that, as it's being generated for every time `initTestSuite` gets called. I would prefer to still notify people at least in some form or another though.

**Comment by psexton** [comment]
I also think there are valid reasons to keep using xunit post-2013 (existing tests, additional outputs, openness). 

I strive to not leave old users in the dust, with any of the MATLAB libraries I write/maintain. But the relevant changes in R2016b really forced our hand here, and there doesn't seem be to be any solution that can handle all of the permutations of MATLAB versions and test types perfectly, other than maintain two parallel release lines, which I'm not willing to do.

A patch so that you only get the warning once per `runxunit` invocation would be nice.
