### ISSUE TITLE
Tests in `tests/src/*` are not run by default

### ISSUE THREAD

**Issue by Nzbuu** [psexton/matlab-xunit#22]
The command in the `Readme.md` file (`runxunit ./tests`) only runs the tests that are directly in the `tests` directory and not those in the sub-directories, especially `./tests/src/` etc.

**Comment by psexton** [comment]
I don't want to change the default behavior to look in subdirectories, as that may break existing installs. (Although a `--recursive` isn't out of the question.)

Any unit tests for xunit that are in subdirectories and are supposed to be run on their own (as opposed to being tests that another unit test runs) are probably an oversight, and should be moved up to the top level.

**Comment by Nzbuu** [comment]
I haven't looked at it yet, but https://github.com/psexton/matlab-xunit/pull/23 is supposed to address this.
